// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA9vE4wdj-0gCMxgkyEFI0LMxEnCCyuAU',
    appId: '1:317105142674:web:4f930a5696fa67b9949f4b',
    messagingSenderId: '317105142674',
    projectId: 'cargo-nomade-ece3b',
    authDomain: 'cargo-nomade-ece3b.firebaseapp.com',
    storageBucket: 'cargo-nomade-ece3b.firebasestorage.app',
    measurementId: 'G-7QHZ7VSPV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDot1DII3TJy_16B9a8whJMa8rMZg4j1LM',
    appId: '1:317105142674:android:53cb4916ae5e7b34949f4b',
    messagingSenderId: '317105142674',
    projectId: 'cargo-nomade-ece3b',
    storageBucket: 'cargo-nomade-ece3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkgyejKzB1aCG58yGGN_oU6noCf6fzeck',
    appId: '1:317105142674:ios:a8f7287f6a841507949f4b',
    messagingSenderId: '317105142674',
    projectId: 'cargo-nomade-ece3b',
    storageBucket: 'cargo-nomade-ece3b.firebasestorage.app',
    iosBundleId: 'com.example.cargoNomade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkgyejKzB1aCG58yGGN_oU6noCf6fzeck',
    appId: '1:317105142674:ios:a8f7287f6a841507949f4b',
    messagingSenderId: '317105142674',
    projectId: 'cargo-nomade-ece3b',
    storageBucket: 'cargo-nomade-ece3b.firebasestorage.app',
    iosBundleId: 'com.example.cargoNomade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA9vE4wdj-0gCMxgkyEFI0LMxEnCCyuAU',
    appId: '1:317105142674:web:6c8a0e7c43b5787d949f4b',
    messagingSenderId: '317105142674',
    projectId: 'cargo-nomade-ece3b',
    authDomain: 'cargo-nomade-ece3b.firebaseapp.com',
    storageBucket: 'cargo-nomade-ece3b.firebasestorage.app',
    measurementId: 'G-RYN2QX5NT9',
  );
}
